name: Deploy Python App on EC2

on:
  workflow_dispatch:
    inputs:
      CLOUD_TYPE:
        description: "Cloud Type"
        required: true
      BLAZEOPS_BASE_URL:
        description: "Base URL for BlazeOps"
        required: true
      branch:
        description: "github branch"
        required: true
      github_token:
        description: "github token"
        required: true
      aws_config:
        description: "AWS Credentials & Region [JSON String]"
        required: true
        type: string
        default: '{}'
      
permissions:
  contents: write
  actions: write



  
